working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 3
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout
      - run: pip install gpu_tpu_lab_server
      - run: from gpu_tpu_lab_server.core import jupyter_lab, vscode, run_process_in_background, run_process_in_foreground
      - run: vscode()
