working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 3
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout
      - run: curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
      - run: curl -fsSL https://code-server.dev/install.sh | sh
      - run: code-server
